### ISSUE TITLE
Couldn't get geometry of requested DOM element

### ISSUE THREAD

**Issue by xtonousou** [asciinema/asciicast2gif#20]
`asciicast2gif` fails to generate .gif files

```bash
$ ./asciicast2gif asciicast.json image.gif

==> Loading asciicast-133781.json...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Couldn't get geometry of requested DOM element
/home/xtonousou/.scripts/others/asciicast2gif/main.js:568
return new Km(a,wf)}function Mm(a){try{var b=a[0];return b.h?b.h(a):b.call(null,a)}catch(e){if(e instanceof Object)throw b=e,a[6].Qc(),b;throw e;}}function Nm(a,b,e){e=Gm(e,Lm(function(e){a[2]=e;a[1]=b;return Mm(a)}));return k(e)?(a[2]=pc(e),a[1]=b,ck):null}function Om(a,b,e){b=b.ld(0,e,Lm(function(b){a[2]=b;a[1]=3;return Mm(a)}));return k(b)?(a[2]=pc(b),a[1]=3,ck):null}function Pm(a,b){var e=a[6];null!=b&&e.ld(0,b,Lm(function(){return function(){return null}}(e)));e.Qc();return e}
                                                                                                                   ^

Error: program exited with code 1
    at ChildProcess.<anonymous> (/home/xtonousou/.scripts/others/asciicast2gif/main.js:1028:100)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

The .json file is the one mentioned  [here]

```bash
$ uname -a

Linux hyperi0n 4.12.6-1-ARCH #1 SMP PREEMPT Sat Aug 12 09:16:22 CEST 2017 x86_64 GNU/Linux
```

[here]: https://github.com/asciinema/asciinema/blob/master/doc/asciicast-v1.md#example-asciicast

**Comment by sickill** [comment]
What are your Node.js and PhantomJS versions?

**Comment by xtonousou** [comment]
Well, it's been a while since I used `asciicast2gif`, so I fetched the latest commits, built and reinstalled it.
The JSON file that has been used is [this](https://asciinema.org/a/133946.json).

### Getting Started

```bash
$ ./asciicast2gif 133946.json 133946.gif
==> Loading 133946.json...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Couldn't get geometry of requested DOM element
/home/xtonousou/asciicast2gif/main.js:568
return new Km(a,wf)}function Mm(a){try{var b=a[0];return b.h?b.h(a):b.call(null,a)}catch(e){if(e instanceof Object)throw b=e,a[6].Qc(),b;throw e;}}function Nm(a,b,e){e=Gm(e,Lm(function(e){a[2]=e;a[1]=b;return Mm(a)}));return k(e)?(a[2]=pc(e),a[1]=b,ck):null}function Om(a,b,e){b=b.ld(0,e,Lm(function(b){a[2]=b;a[1]=3;return Mm(a)}));return k(b)?(a[2]=pc(b),a[1]=3,ck):null}function Pm(a,b){var e=a[6];null!=b&&e.ld(0,b,Lm(function(){return function(){return null}}(e)));e.Qc();return e}
                                                                                                                   ^

Error: program exited with code 1
    at ChildProcess.<anonymous> (/home/xtonousou/asciicast2gif/main.js:1028:100)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Node.js Version

```bash
$ node --version
v8.6.0
```

### PhantomJS Version

```bash
$ phantomjs --version
2.1.1
```

### Kernel

```bash
Linux hyperi0n 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 GNU/Linux
```

**Comment by sickill** [comment]
I just tried it on the linked asciicast, directly on my macOS and also via Docker, and worked fine in both cases. 

🤔

**Comment by masaeedu** [comment]
#20, #44, and #50 (so far) seem to be duplicates. Could anyone who's seeing this issue please run with `DEBUG=1 asciicast2gif ...` and see if the message `console.log: Failed to pre-load Powerline Symbols font` appears alongside the rest of the output?

**Comment by masaeedu** [comment]
I suspect this might be an issue with missing fonts on the system. The logic in `fontfaceonload.js` sis doing some kind of analysis of font heights and widths that I can't understand, but if I just tweak `options.error()` on line 129 to `options.success()`, it starts to work for me.

**Comment by sickill** [comment]
@masaeedu good job on spotting this! 🏆 

Problem with `FontFaceOnload` will `callPhantom` with `null` rect, and the other part of the code will log this "can't get geometry" error when rect is `null`. This is likely it.

The reason I used `FontFaceOnload` is that, without solution like this it's possible that first few screenshots will not have Powerline symbols rendered (until the font loads in Phantom). It's a race condition thing. It may be that it actually does more harm than good though....

**Comment by sickill** [comment]
And, actually even more likely problem is that when you run `asciicast2gif` directly on your host (not via Docker) then you don't have Powerline Symbols on your system, and then it always fails 🤔

**Comment by masaeedu** [comment]
@sickill Is there a way to fallback here if the font isn't present in the system? If I just bypass this check using the hack I described things still seem to work fine.

**Comment by sickill** [comment]
I just remembered that this font is embedded in the html file (https://github.com/asciinema/asciicast2gif/blob/master/page/asciicast2gif.html#L10), so it's always there. It could be that when running directly you can have different version of PhantomJS which cannot handle this inline font definition properly 🤔 

Anyway, since the font is there, loading it should it either be instant, or it will never happen. So after 1s wait we could just proceed like it had succeeded (only small subset of users use Powerline anyway).

**Comment by sickill** [comment]
@doronbehar when cloning this repo you need `--recursive` flag (see here https://github.com/asciinema/asciicast2gif#building-from-source) to get git submodules cloned too.

Run `git submodule update --init --recursive` and try again.

**Comment by doronbehar** [comment]
Confirmed.

**Comment by funilrys** [comment]
Hi @sickill,
just wanted to confirm that the patch fixes the issue.

Also @cbrake, there is an AUR package: https://aur.archlinux.org/packages/nodejs-asciicast2gif/

**Comment by sickill** [comment]
@funilrys thx!
