### ISSUE TITLE
Unicode not rendered

### ISSUE THREAD

**Issue by nkh** [asciinema/asciicast2gif#23]
I have a demo where a tree is rendered with unicode, the tree is not visible in the generated gif.

**Comment by sickill** [comment]
Can you provide an example recording json file and the gif that's missing the characters?

**Comment by nkh** [comment]
![demo](https://user-images.githubusercontent.com/45409/31083147-2bf0b03e-a791-11e7-937c-19c17fab63ed.gif)

[demo_error.json.gz](https://github.com/asciinema/asciicast2gif/files/1349256/demo_error.json.gz)

**Comment by frioux** [comment]
I have the same experience, with 💀 🕛

**Comment by sickill** [comment]
I think it's related to this problem: https://github.com/asciinema/asciinema-player/issues/59
Both a2png (which generates png thumbnail) and asciicast2gif use similar phantomjs based renderer.

**Comment by kermat** [comment]
I had a similar issue rendering "box drawing glyphs" with asciidoctor using common fonts. I ended up switching to GNU Unifont for rendering "code blocks"; GNU Unifont includes these characters. Hope that little bit of information is helpful.

**Comment by ku1ik** [comment]
To anyone who stumbled upon this: try asciicast2gif's successor - https://github.com/asciinema/agg . It renders characters differently, doesn't suffer from this problem.
