### ISSUE TITLE
How to change font of asciicast2gif

### ISSUE THREAD

**Issue by yulivee** [asciinema/asciicast2gif#28]
Hi all around! I love asciinema and this script is just great!

I created an asciinema recording in my terminal. the terminal uses the font Meslo for powerline. Recording works nicely, playing it works nicely. The gif can be created using this tool, but unfortunately with the gif, a non-monospaced font is used instead of Meslo (Looks like default sans serif). As you can image this looks quite messy in a terminal.

I did not understand which part of the process picks the font when creating the gif-image. Where do I have to change the font to a monospaced one?

Cheers,
Sandra

**Comment by sickill** [comment]
Hey Sandra,

asciicast2gif uses PhantomJS which renders terminal using the stylesheet from asciinema-player (here's the font part: https://github.com/asciinema/asciinema-player/blob/develop/src/less/modules/_font.less#L2)

What's the difference between Menlo and Meslo?

Have you installed asciicast2gif with npm or used Docker image?

**Comment by yulivee** [comment]
Hi sickill,
thanks for you quick response. I installed asciicast2gif using npm and asciinema using pip installer.

I am working with Ubuntu Linux and checked my installed fonts. I only have Bitstream Vera Sans installled from the font list in the file you referenced.

Menlo seems to be a Mac OS font. Consolas a Windows Font. Meslo is a powerline enabled font I downloaded, its a modified version of the Menlo font (https://github.com/andreberg/Meslo-Font).

I will try to compile asciinema form source and see if that helps

**Comment by sickill** [comment]
asciinema command is not used for gif generation, so its version doesn't matter.

So, if we added Meslo to the `font-family` list it could probably solve it, right?

**Comment by yulivee** [comment]
I am not shure as the 'Bitstream Vera Sans' is present on my system and should have been picked, but didn't. I am going to experiment with this list and will let you know of the results

**Comment by sickill** [comment]
@yulivee  Have you had a chance to figure out why it doesn't pick up the proper font on your system? Can we close this issue?

**Comment by yi-jiayu** [comment]
Ran into this issue on Ubuntu 16.04 on Windows Subsystem for Linux and `asciicast2gif` installed through npm.

Here is how the gifs look like with the sans-serif font:
![download-comments-sans-serif](https://user-images.githubusercontent.com/11734309/39080185-482abb6e-455c-11e8-9d38-5e0f1813358b.gif)

Installing Bitstream Vera Sans Mono from the `font-family` list at https://github.com/asciinema/asciicast2gif/blob/master/page/asciinema-player.css#L144 with `sudo apt install ttf-bitstream-vera` doesn't help:

```
$ fc-list | grep 'Bitstream Vera Sans Mono'
/usr/share/fonts/truetype/ttf-bitstream-vera/VeraMoBI.ttf: Bitstream Vera Sans Mono:style=Bold Oblique
/usr/share/fonts/truetype/ttf-bitstream-vera/VeraMoBd.ttf: Bitstream Vera Sans Mono:style=Bold
/usr/share/fonts/truetype/ttf-bitstream-vera/VeraMono.ttf: Bitstream Vera Sans Mono:style=Roman
/usr/share/fonts/truetype/ttf-bitstream-vera/VeraMoIt.ttf: Bitstream Vera Sans Mono:style=Oblique
```

However, removing everything except `monospace, 'Powerline Symbols'` fixed it for me:
```diff --git a/page/asciinema-player.css b/page/asciinema-player.css
index 164edf7..d3f6369 100644
--- a/page/asciinema-player.css
+++ b/page/asciinema-player.css
@@ -141,7 +141,7 @@
   border-style: solid;
   cursor: text;
   border-width: 0.5em;
-  font-family: Consolas, Menlo, 'Bitstream Vera Sans Mono', monospace, 'Powerline Symbols';
+  font-family: monospace, 'Powerline Symbols';
   line-height: 1.3333333333em;
 }
 .asciinema-terminal .line {
```

![download-comments](https://user-images.githubusercontent.com/11734309/39080281-4be740d2-455d-11e8-8857-b7775d24b7e9.gif)

Hope this helps!

**Comment by ku1ik** [comment]
asciicast2gif is no longer maintained, but fortunatelly there's new tool for gif generation I just published - https://github.com/asciinema/agg

`agg` has `--font-family` and `--font-dir` options to customize font rendering so you can try it instead.
