### ISSUE TITLE
file could not be opened error

### ISSUE THREAD

**Issue by jwoertink** [asciinema/asciicast2gif#29]
I built from source, and tried running from both a remote asciinema url as well as a downloaded json file. The script fully completes with no errors, but when the gif is generated, I can't open it.
```
[09:12AM] asciicast2gif (master)$ asciicast2gif ~/Desktop/147415.json ~/Desktop/demo.gif
==> Loading /Users/jeremywoertink/Desktop/147415.json...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Combining screenshots into GIF file...
==> Done.
```

<img width="532" alt="screen shot 2017-11-14 at 9 24 47 am" src="https://user-images.githubusercontent.com/2391/32794421-ac512c4c-c91d-11e7-87dc-3df712b1a48a.png">

npm 4.6.1
lein Leiningen 2.8.1 on Java 1.8.0_144 Java HotSpot(TM) 64-Bit Server VM
macOS 10.13.1

**Comment by publicarray** [comment]
Did you try to open the gif in another program, for example a browser? I could generate and open the file in both chrome and firefox

**Comment by publicarray** [comment]
You can also use ffmpeg to recreate/fix the gif 
```bash
ffmpeg -ss 30 -t 3 -y -i demo.gif -vf fps=10,scale=1920:-1:flags=lanczos,palettegen palette.png
ffmpeg -i demo.gif -i palette.png -filter_complex "fps=10,scale=1920:-1:flags=lanczos[x];[x][1:v]paletteuse" output.gif
```
However the output will be a bit larger in file size. You can use [gifsicle](http://www.lcdf.org/gifsicle/) or [ImageOptim](https://imageoptim.com/) to  compress it.

**Comment by jwoertink** [comment]
I ran that command, and it generated the file on my desktop, then I double clicked the file, and got that error.

**Comment by sickill** [comment]
@jwoertink can you post such broken gif file somewhere so someone can look closer?

**Comment by jwoertink** [comment]
hmm... That's interesting. [Here's a link](https://www.dropbox.com/s/3p9jg1dzs59cr0x/demo.gif?dl=0). Looks like it works in the browser, just not on the desktop.

**Comment by publicarray** [comment]
@jwoertink the commands [above](https://github.com/asciinema/asciicast2gif/issues/29#issuecomment-346347335) should work, the gif after I ran the commands:
![output](https://user-images.githubusercontent.com/5497998/33151872-a2307146-d025-11e7-9cb4-0a6a2e6bc30e.gif) The preview app is able to open it fine, but I don't think that the Preview app is really designed to open gifs anyway.

**Comment by jwoertink** [comment]
The preview app works fine with gif 
![screen shot 2017-11-22 at 2 27 04 pm](https://user-images.githubusercontent.com/2391/33152508-dc9d658a-cf91-11e7-896c-af96728c6cad.png)

The ones generated with this also won't work if sent to someone via text. I guess if it's only going to support web, then maybe a note could just be added to the README?

**Comment by publicarray** [comment]
Sorry I should have been clearer, the preview app works on (apparently only some) gifs but is not 'designed' for gifs it just displays singe frames. It looks like an after-thought on Apples part IMHO.

I have two asciinema json files that once is converted via asciicast2gif open fine in the Preview app.

**Comment by jwoertink** [comment]
ok
