### ISSUE TITLE
Generated GIFs are very inefficient in space

### ISSUE THREAD

**Issue by ahmetb** [asciinema/asciicast2gif#31]
Take a look at this GIF, it goes on FOR MINUTES and it's only 32 kb:

https://github.com/tianon/gosleep/blob/master/example.gif
[![](https://github.com/tianon/gosleep/blob/master/example.gif?raw=true)](https://github.com/tianon/gosleep/blob/master/example.gif?raw=true)

I'm curious why we can't we have this minimality with `asciicast2gif`? My 30 second recording is **964 kilobytes**. 

Is there a way to minimalize this? I don't care about antialiasing and all those fancy stuff making the image larger.

**Comment by publicarray** [comment]
There are many factors to the file size. The example.gif is only 497×290 pixels, uses few colours, is short (~28 seconds) and has a low area of change between frames (easier to compress).
 
asciicast2gif already uses [gifsicle](http://www.lcdf.org/gifsicle/) to compress the output gif, but there are more options from gifsicle that you can try.

**Comment by publicarray** [comment]
You can also ask @tianon how the gif was generated.

**Comment by tianon** [comment]
Was a pretty standard byzanz (https://github.com/GNOME/byzanz) recording -- nothing very custom there.

**Comment by publicarray** [comment]
Thanks for chiming in. Cool project for GNOME users.

**Comment by tianon** [comment]
Heh, I don't use GNOME -- I actually ran it inside a Docker container, and had a small wrapper script to grab the proper X, Y, width, and height for capturing the window I was interested in.  It doesn't need more than the X11 socket in order to work. :+1:

**Comment by sickill** [comment]
@ahmetb can you give us a link to your recording which ends up being 964kb gif? We can play with various arguments for asciicast2gif and for gifsicle.

**Comment by ahmetb** [comment]
https://asciinema.org/a/dD9UhCIaPw13znirhmGUnNJtd

**Comment by publicarray** [comment]
I've played a little with ImageMagick and gifsicle

|Command|Size (KB)|Savings (KB)|
|-|-|-|
|`asciicast2gif 'https://asciinema.org/a/dD9UhCIaPw13znirhmGUnNJtd.cast?dl=true' out.gif`|941|0|
|`asciicast2gif 'https://asciinema.org/a/dD9UhCIaPw13znirhmGUnNJtd.cast?dl=true' out.gif -S 1` *|348|593|
|`gifsicle --optimize -O3 --colors 16 -o out-16.gif out.gif`|336|593+12|
|`convert out.gif -coalesce -layers RemoveDups -layers RemoveZero -layers OptimizeFrame out-dedupe.gif`|321|593+27|
|<code>convert out.gif -coalesce -layers RemoveDups -layers RemoveZero -layers OptimizeFrame - &#124; gifsicle --optimize -O3 -o out-dedupe-gifsicle.gif</code>|259|593+89|
|<code>convert out.gif -coalesce -layers RemoveDups -layers RemoveZero -layers OptimizeFrame - &#124; gifsicle --optimize -O3 --colors 16 -o out-dedupe-16.gif</code>|253|593+95|
|<code>convert out.gif -coalesce -layers RemoveDups -layers RemoveZero -layers OptimizeFrame - &#124; gifsicle --optimize -O3 --colors 6 --use-colormap=gray -o out-dedupe-bw.gif</code>|175|593+173|


&#42; The scaled=1 gif is used as an input for all remaining commands

**Comment by sickill** [comment]
@publicarray awesome! That's very helpful.

Another things to try:

- check out giflossy instead of gifsicle (see #1)
- use gifsicle to assemble frames instead of ImageMagick (see #3)

I'm thinking that maybe asciicast2gif could have a concept of "presets", probably 3 (low, normal, high) would be enough to cover everyone's needs. But before presets, I'd like to try the above.

**Comment by ahmetb** [comment]
It'd be really cool to script into a separate tool, or bundle in the asciicast2gif tool?

**Comment by sickill** [comment]
I've implemented some optimizations:

- the biggest impact on filesize was too high frame-rate - it's capped at 15fps now
- added support for giflossy (if giflossy is installed instead of gifsicle the options passed to gifsicle command are extended with `-lossy=80`)

I've pushed new version to npm, and there's new image on Docker hub (`docker pull asciinema/asciicast2gif` if you previously pulled it).

You can set `GIFSICLE_OPTS` env var to override the options passed to gifsicle, which is great for experimenting with different color/optimization/lossyiness combinations.

**Comment by sickill** [comment]
I've generated gif from the asciicast linked by @ahmetb using latest (today's) version, with this command:

    asciicast2gif -S 1 https://asciinema.org/a/dD9UhCIaPw13znirhmGUnNJtd.cast ahmetb.gif

Or Docker version:

    docker run --rm -v $PWD:/data asciinema/asciicast2gif -S 1 https://asciinema.org/a/dD9UhCIaPw13znirhmGUnNJtd.cast ahmetb.gif

The resulting gif is 213kb, which is a good improvement over initial 964kb.

![ahmetb](https://user-images.githubusercontent.com/17589/38354682-ba37e762-38ba-11e8-8098-6005ef4f598f.gif)

**Comment by ahmetb** [comment]
Thanks a bunch, that's a pretty good improvement!
