### ISSUE TITLE
Some characters like ─ are not rendered

### ISSUE THREAD

**Issue by ahmetb** [asciinema/asciicast2gif#32]
This "─ " character is used by tmux to separate panes. When I convert this using asciicast2gif, I lose this character, and it appears as empty/space.

Repro: https://asciinema.org/a/dD9UhCIaPw13znirhmGUnNJtd

Supposed to look like:
![image](https://user-images.githubusercontent.com/159209/34093619-1643e41c-e37e-11e7-900f-0ee3d94eff44.png)

Looks like
![image](https://user-images.githubusercontent.com/159209/34093628-1eb9a366-e37e-11e7-93b2-90936fc83e13.png)

**Comment by ssbarnea** [comment]
True, i discovered myself that some things are missing from the rendered version.

**Comment by ahmetb** [comment]
Anyone willing to fix this? Over a year later, I hit this again. Anytime I'm trying to record some cool interactive CLI tool using somewhat special characters, it won't show up in the recording.

**Comment by ahmetb** [comment]
Have you ran it directly, or inside a container through the Docker image provided in readme.md. I’ve observed this in all sorts of special characters outside the ascii table.

It might have been because asciinema2gif being on a modern system vs inside a linux container.

**Comment by mathieu-aubin** [comment]
directly is what i have done, cant lie about that.
did you rebuild the container? made sure gifsicle / asciicast2gif are up to date inside said container? i will check the docker file and see once i get a chance

**Comment by mathieu-aubin** [comment]
if you can modify the docker file (as i have no time atm) ...
instead of downloading giflossy straight from an archive/url, try installing node, then npm, then installing gifsicle with npm
    npm i gifsicle -g

**Comment by mathieu-aubin** [comment]
gifsicle doesnt support gzip tho so from url wont work. you will need to grab the file first or work some linux pipes as i did

**Comment by ku1ik** [comment]
Closing as asciicast2gif is dead. Try https://github.com/asciinema/agg instead.
