### ISSUE TITLE
Does asciicast2gif ignore 'idle_time_limit'?

### ISSUE THREAD

**Issue by hjmallon** [asciinema/asciicast2gif#34]
WARNING: I could be completely wrong here and my javascript is not good so I haven't checked.

The 'idle_time_limit' function of asciinema rec is not working when I use asciicast2gif from the resulting json file. I just went through and retimed my recording manually to work around the problem.

**Comment by sickill** [comment]
Have you installed via npm or used Docker image?

**Comment by hjmallon** [comment]
I am using the npm version on macOS

**Comment by hjmallon** [comment]
I just tested with this and I am pretty sure it is ignoring the 'idle_time_limit'. Playing this back with asciinema play works fine.
[test.txt](https://github.com/asciinema/asciicast2gif/files/1738308/test.txt)

**Comment by sickill** [comment]
I can reproduce it. Looking for a fix.

**Comment by sickill** [comment]
Fixed via a5fd083f430d98d27b5a8dd1c7ee550233ebfce3

**Comment by sickill** [comment]
I've released new npm package.
