### ISSUE TITLE
How can I patch the client object to support self-signed SSL Cert protected urls

### ISSUE THREAD

**Issue by joshisa** [asciinema/asciicast2gif#36]
Inspecting main.cljs, I think that I need to provide an options object to the http client object.
```
(defn- http-get [url ch]
  (let [proto (-> url (str/split #":") first)
        gunzip (.createGunzip zlib)
        client (nodejs/require proto)]
    (.get client url (fn [res]
[...]
```
I should be able to generically attach the **rejectUnauthorized** parameter within an options object with a default value of true.  I can't figure out the syntax to accomplish this.

Any hints on the best way to proceed?

**Comment by sickill** [comment]
Hey. I will try to help you if you show me how this would be done in pure JS :)
`var client = require("http"); client.rejectUnauthorized = true`?

Btw, I've setup a forum at https://discourse.asciinema.org/ which is generally a better place to ask for help (you didn't find it because I haven't linked to it anywhere yet). A hint for the future.

**Comment by joshisa** [comment]
@sickill Awesome.  Really appreciate your help.  Also, thanks for the reference to the forum.  Will use that in the future for guidance questions.  Finally, wanted to share my enthusiasm for this sweet project.  So many cool directions to use and benefit from it.

Symptom
---
```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1041:34)
    at TLSSocket.emit (events.js:160:13)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
```
Workaround 1 :: (Global Env Var Approach)
---
```
export NODE_TLS_REJECT_UNAUTHORIZED=0
$ asciicast2gif https://asciinema.org/a/113199.cast demo.gif
$ ==> Loading https://asciinema.org/a/113199.cast...
$ ==> Spawning PhantomJS renderer...
[....]
```
**Downside**:  Is global to my client/laptop - reducing security very broadly.

Workaround 2 :: (JS Approach to inform Clojurescript Modification)
---
>Pay special attention to the **rejectUnauthorized** key.  By toggling its default value from **true** to **false**, the request is now able to succeed in spite of the bad SSL certificate presented.
```
const https = require('https')

var options = {
    hostname: 'expired.badssl.com',
    port: 443,
    path: '/',
    method: 'GET',
    rejectUnauthorized: true,
    agent: false
  };

console.log("GET REQUEST",options);

https.request(options, function(res) {
  console.log('STATUS: ' + res.statusCode);
  console.log('HEADERS: ' + JSON.stringify(res.headers));
  res.setEncoding('utf8');
  res.on('data', function (chunk) {
    console.log('BODY: ' + chunk);
  });
}).end();
```
<p align="center">
  <img width="600" src="https://cdn.rawgit.com/joshisa/icpascii/master/examples/rejectUnauthorized.svg">
</p>

**Comment by joshisa** [comment]
One possible outcome could be consideration for an `--insecure` flag that when set implies a setting of **false** for the rejectUnauthorized key:value pair and a presumed ssl url path with a certificate problem.

`usage: asciicast2gif [--insecure] [-t theme] [-s speed] [-S scale] [-w columns] [-h rows] <input-json-path-or-url> <output-gif-path>`

**Comment by sickill** [comment]
If you prepend the command with env var like this:

    $ NODE_TLS_REJECT_UNAUTHORIZED=0 asciicast2gif https://some.host/a/113199.cast demo.gif

then the env var will only be set for the started command, and the rest of your system will be secure. No need to export the var.

Would that be good solution? You can also wrap that in a simple shell script.
I would prefer to not add a flag for the purpose of lowering the security if there is other way :)

**Comment by joshisa** [comment]
@sickill That's a fair point.  I'm comfortable closing this.  From a learning perspective, I'd still welcome your thoughts/hints on how to approach monkey-patching the main.cljs to better understand how the http client options are managed for the GETs.
