### ISSUE TITLE
Install with npm failing

### ISSUE THREAD

**Issue by standage** [asciinema/asciicast2gif#39]
When I try to install with npm I get some warning messages. I'm not sure which of these is critical, if any, but I cannot execute `asciicast2gif` after the install.

See the following terminal recording because of course. :-)

[![asciicast](https://asciinema.org/a/Q6QUtOxNRp6Pz4DhziS4I8KS2.png)](https://asciinema.org/a/Q6QUtOxNRp6Pz4DhziS4I8KS2)

**Comment by cedricium** [comment]
I too am seeing this issue. My specs:
- **Operating System:** macOS High Sierra 10.13.3
- **Shell:** zsh (with oh-my-zsh)
- **Terminal:** iTerm2

```sh
$ node -v  # v8.11.1
$ npm -v   # 5.6.0
```

**Comment by sickill** [comment]
The `npm install` command in readme didn't have `-g` (or `--global`) and so it didn't install the binary for you. It's been fixed in #40.

Can you try with `npm install -g asciicast2gif` again?

**Comment by cedricium** [comment]
@sickill can confirm that worked for me 👍
