### ISSUE TITLE
some characters are not visible

### ISSUE THREAD

**Issue by igordot** [asciinema/asciicast2gif#45]
I tried converting a recording to a GIF.
```
docker run --rm -v $PWD:/data asciinema/asciicast2gif https://asciinema.org/a/193932.json 193932.gif
```

The original on the website looks fine:
[![asciicast](https://asciinema.org/a/193932.png)](https://asciinema.org/a/193932)

But as you can see, the GIF is not:
![193932](https://user-images.githubusercontent.com/6363505/43361778-7d1e44d8-92a7-11e8-88b4-f5c3fbf2db71.gif)

In a possibly related issue, the thumbnail on the website is fine, but not in the embed.

**Comment by dnozay** [comment]
There is a copy of Bistream Vera Mono that has been patched with a lot of symbols: https://github.com/ryanoasis/nerd-fonts
`Powerline symbols` is nice, but does not cover all the symbols used in other popular `zsh` themes, eg. `powerlevel9k` and `powerlevel10k`

With default docker image:
![test2](https://user-images.githubusercontent.com/205466/70575012-58db6000-1b5a-11ea-8d4c-6f223701bda6.gif)

Tested locally, adding the patched font in the system:
```
FROM asciinema/asciicast2gif
COPY BitstreamVeraSansMonoNerdFontComplete.ttf /usr/share/fonts/truetype
```

![test](https://user-images.githubusercontent.com/205466/70575011-58db6000-1b5a-11ea-9aa0-54ecdc40d746.gif)

**Comment by dnozay** [comment]
```
FROM asciinema/asciicast2gif

# for unicode emojis
RUN wget https://github.com/eosrei/twemoji-color-font/releases/download/v12.0.1/TwitterColorEmoji-SVGinOT-Linux-12.0.1.tar.gz && \
    tar zxf TwitterColorEmoji-SVGinOT-Linux-12.0.1.tar.gz && \
    cd TwitterColorEmoji-SVGinOT-Linux-12.0.1 && \
    cp TwitterColorEmoji-SVGinOT.ttf /usr/share/fonts/truetype

# for zsh powerline + nerd fonts
COPY BitstreamVeraSansMonoNerdFontComplete.ttf /usr/share/fonts/truetype

# for more unicode emojis
COPY NotoColorEmoji.ttf /usr/share/fonts/truetype
COPY NotoEmoji-Regular.ttf /usr/share/fonts/truetype

# for correct box drawing
RUN apt-get update && \
    apt-get -y install ttf-ancient-fonts && \
    rm -rf /var/lib/apt/lists/*
```
```
docker build --tag asciicast2gif:nerdfont .
docker run --rm -v $PWD:/data asciicast2gif:nerdfont \
   asciinema/asciicast2gif https://asciinema.org/a/193932.json test.gif
```

![original-issue](https://user-images.githubusercontent.com/205466/70577857-f043b180-1b60-11ea-94fb-36b8a64b7fb7.gif)

**Comment by greyltc** [comment]
I guess my issue is a font one too.
```
docker run --rm -v $PWD:/data asciinema/asciicast2gif https://asciinema.org/a/327214.json out2.gif
```
Doesn't generate the appropriate gif.

Any chance we can get an updated official docker image with some more/fixed fonts?

**Comment by ku1ik** [comment]
Closing as asciicast2gif is dead. Try https://github.com/asciinema/agg instead.
