### ISSUE TITLE
Converted GIF color mismatch

### ISSUE THREAD

**Issue by Qinusty** [asciinema/asciicast2gif#47]
I generated a [GIF](https://i.imgur.com/VDgwxoU.jpg)  using the command `docker run --rm -v $PWD:/data asciinema/asciicast2gif -s 2 -t solarized-dark recording.json recording.gif`

The GIF does not match the colours recorded from `asciinema rec`. The original can be found [here](https://asciinema.org/a/T2BR58Pt27f1YMz2kEDZXyFLy).

Is this due to an 8 bit colour limitation? Either way, my shell prompt has green in it, whereas the SUCCESS messages are grey.

**Comment by sickill** [comment]
asciicast2gif runs gifsicle with `-k 64` which generates 64 color output. How does this look in your terminal? 

It looks to me like green is actually grey-ish in Solarized Dark. Here's your recording in Solarized:

https://asciinema.org/a/T2BR58Pt27f1YMz2kEDZXyFLy?theme=solarized-dark
