### ISSUE TITLE
Corrupt / Degraded gif Output

### ISSUE THREAD

**Issue by ossie-git** [asciinema/asciicast2gif#49]
Hi,

I recently started using asciicast2gif and have successfully used it a number of times.  I use the Docker image

However, while processing a somewhat long demo, the results were less than optimal and the screen output looks wrong

Here is the command:

```
docker run --rm -v $PWD:/data asciinema/asciicast2gif demo.cast.1 demo.cast.1.gif                                     ==> Loading demo.cast.1...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Combining 607 screenshots into GIF file...
gifsicle: warning: huge GIF, conserving memory (processing may take a while)
==> Done.
```

What it looks like via asciinema - asciinema_play.png
![asciinema_play](https://user-images.githubusercontent.com/25382296/46935343-9ce1ea80-d0a6-11e8-8378-a03fb8eea4fb.png)

What the generated gif looks like - asciicast2gif.jpg
<img width="1436" alt="asciicast2gif" src="https://user-images.githubusercontent.com/25382296/46935333-93588280-d0a6-11e8-980a-fa571fa7ac13.png">

I haven't run into this problem in shorter casts.  Any ideas?  Thanks.

**Comment by sickill** [comment]
That looks quite bad indeed. It's either imagemagick or gifsicle doing something fuzzy here.

**Comment by tucked** [comment]
Just hit this... `-S 1` helped

**Comment by socketbox** [comment]
@tucked 's workaround cleared up the artifacts/ghosting but not being able to increase the size of the font is less than ideal.

**Comment by ku1ik** [comment]
You may want to try out https://github.com/asciinema/agg , which is a successor to asciicast2gif I just released.
