### ISSUE TITLE
taking a long time...

### ISSUE THREAD

**Issue by lalan7** [asciinema/asciicast2gif#51]
I run this command:

i run this in alias : 

`asciicast2gif='docker run --rm -v $PWD:/data asciinema/asciicast2gif'
`
then i ran the following command:

`asciicast2gif demosprint.cast demosprint.gif`

```
==> Loading demosprint.cast...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Combining 1131 screenshots into GIF file...
```

And now is seem to be stuck there forever. A long normaly should this take ?

thx

**Comment by lalan7** [comment]
Finally finish we this error:

```
convert: unable to write pixel cache `/tmp/magick-29fn6FcP36q2mC': No space left on device @ error/cache.c/WritePixelCachePixels/5492.
convert: Too many IDAT's found `/tmp/tmp.KQuSBHp7HZ/1094.png' @ error/png.c/MagickPNGErrorHandler/1643.
.....
convert: Too many IDAT's found `/tmp/tmp.KQuSBHp7HZ/1127.png' @ error/png.c/MagickPNGErrorHandler/1643.
convert: corrupt image `/tmp/tmp.KQuSBHp7HZ/1127.png' @ error/png.c/ReadPNGImage/3973.
convert: unable to write pixel cache `/tmp/magick-29Tl_q7GLqRiIC': No space left on device @ error/cache.c/WritePixelCachePixels/5492.
convert: Too many IDAT's found `/tmp/tmp.KQuSBHp7HZ/1128.png' @ error/png.c/MagickPNGErrorHandler/1643.
convert: corrupt image `/tmp/tmp.KQuSBHp7HZ/1128.png' @ error/png.c/ReadPNGImage/3973.
convert: unable to write pixel cache `/tmp/magick-294uV8FtIbmAeT': No space left on device @ error/cache.c/WritePixelCachePixels/5492.
convert: Too many IDAT's found `/tmp/tmp.KQuSBHp7HZ/1129.png' @ error/png.c/MagickPNGErrorHandler/1643.
convert: corrupt image `/tmp/tmp.KQuSBHp7HZ/1129.png' @ error/png.c/ReadPNGImage/3973.
convert: unable to write pixel cache `/tmp/magick-29BMBPgDfJRcR9': No space left on device @ error/cache.c/WritePixelCachePixels/5492.
convert: Too many IDAT's found `/tmp/tmp.KQuSBHp7HZ/1130.png' @ error/png.c/MagickPNGErrorHandler/1643.
convert: corrupt image `/tmp/tmp.KQuSBHp7HZ/1130.png' @ error/png.c/ReadPNGImage/3973.
convert: unable to write pixel cache `/tmp/magick-29h15xjBUD74Bq': No space left on device @ error/cache.c/WritePixelCachePixels/5492.
convert: unable to extend cache `/tmp/tmp.KQuSBHp7HZ/0.png': No space left on device @ error/cache.c/OpenPixelCache/3682.
convert: unable to write pixel cache `/tmp/magick-29h15xjBUD74Bq': No space left on device @ error/cache.c/WritePixelCachePixels/5492.
convert: unable to extend cache `/tmp/tmp.KQuSBHp7HZ/0.png': No space left on device @ error/cache.c/OpenPixelCache/3682.
convert: unable to write pixel cache `/tmp/magick-29h15xjBUD74Bq': No space left on device @ error/cache.c/WritePixelCachePixels/5492.
convert: unable to extend cache `/tmp/tmp.KQuSBHp7HZ/0.png': No space left on device @ error/cache.c/OpenPixelCache/3682.
convert: unable to write pixel cache `/tmp/magick-29h15xjBUD74Bq': No space left on device @ error/cache.c/WritePixelCachePixels/5492.
convert: unable to extend cache `/tmp/tmp.KQuSBHp7HZ/0.png': No space left on device @ error/cache.c/OpenPixelCache/3682.
gifsicle: warning: trivial adaptive palette (only 2 colors in source)
```
the ouput of the gif is : 

![image](https://user-images.githubusercontent.com/14317740/47918189-2bfe4900-de82-11e8-8b54-54098a7d0931.png)

**Comment by sickill** [comment]
`Combining 1131 screenshots into GIF file` - that's quite a lot. 

Anyway, after the above is printed all the 1131 PNGs are passed to imagemagick+gifsicle, this is what takes this time.

Slowness is one thing, but more importantly Docker container went out of disk space.
I'm not quite sure if Docker puts any (artificial) limits on the started containers. Worth investigating.

**Comment by coderkan** [comment]
Hi,

I had the same problem. I waited more than 3 hours and nothing happened. My computer stops responding while running asciicast2gif convert gif.
Is there a limit to convert GIF?

Thanks.
Erkan

**Comment by Vafa-Andalibi** [comment]
same here for a gif with 65 screenshots. It's taking more than 30 minutes on MacOS Mojave. Is this normal?

**Comment by mathieu-aubin** [comment]
@Vafa-Andalibi can you try using my fork and see if it helps?

`git clone --recursive https://github.com/mathieu-aubin/asciicast2gif`

You shouldn't run with docker as it runs an outdated version of gifsicle.

Also, try using the `-S 1` option instead of the default as this will greatly reduce the time spent

You could also set the niceness to -20 to give the app full priority, if you are not running on a super important production server that is (i hope not)

**Comment by mathieu-aubin** [comment]
I've added a new option just now, `-c <color_count` to set GIFSICLE_OPTS colors to the amount you want. Could be useful for black and white casts...

Also, there is better debugging output

**Comment by mhewedy** [comment]
Same issue here with 300 screenshots using:
```
docker run --rm -v $PWD:/data asciinema/asciicast2gif -s 3  https://asciinema.org/a/327940.json vermin-v0.61.0-demo.gif
```
Take forever and doesn't work. (It used to work in past)

BTW, I need to reclaim disk space back from docker using: 
```
> ~/Library/Containers/com.docker.docker/Data/vms/0/Docker.raw
```
which sometimes **corrupt**  docker but reclaim the disk back.

**Comment by mathieu-aubin** [comment]
-S 1

**Comment by mathieu-aubin** [comment]
[![asciicast](https://asciinema.org/a/otAqf5dU73gDQlt1H7M6077Lw.svg)](https://asciinema.org/a/otAqf5dU73gDQlt1H7M6077Lw)

the output gif: 

https://p.4ce.ca/DDgi.gif

**Comment by koalalorenzo** [comment]
at least seeing the progress would help a lot! I am facing the same issue :(

**Comment by mathieu-aubin** [comment]
which progress? Isn't this enough

`docker run --rm -v $PWD:/data asciinema/asciicast2gif -s 3 -S 1 https://asciinema.org/a/327940.json vermin-v0.61.0-demo.gif`

sorry i dont get it

**Comment by mhewedy** [comment]
> [![asciicast](https://camo.githubusercontent.com/9c2b0e39dc18da057de7f3c70fdf282bbc754481/68747470733a2f2f61736369696e656d612e6f72672f612f6f7441716635645537336744516c743148374d363037374c772e737667)](https://asciinema.org/a/otAqf5dU73gDQlt1H7M6077Lw)
> 
> the output gif:
> 
> ![output gif](https://camo.githubusercontent.com/454632bc770304ed8ece3023dec9dc6fb1a3b3c4/68747470733a2f2f702e3463652e63612f444467692e676966)

Thanks. 😍

**Comment by koalalorenzo** [comment]
> which progress? Isn't this enough
> 
> `docker run --rm -v $PWD:/data asciinema/asciicast2gif -s 3 -S 1 https://asciinema.org/a/327940.json vermin-v0.61.0-demo.gif`
> 
> sorry i dont get it

When it is combining the 300 screenshots into the GIF, seeing that it is doing the 299th will help me from interrupting right when it is about to be done :D

**Comment by ku1ik** [comment]
Memory and disk space problems with asciicast2gif have been reported too many times, so I decided to approach this problem in a different way. I played with pure Rust implementation of gif generation and the result is https://github.com/asciinema/agg , which does the job faster, with very low memory usage and no extra disk space needed. Check it out. I don't plan to maintain asciicast2gif anymore. Long live agg!

**Comment by ku1ik** [comment]
I tested agg on @mhewedy's recording:

![x](https://user-images.githubusercontent.com/17589/184540842-f128dfb4-bcde-4e5a-96a9-0012136382ab.gif)

Result:

![327940](https://user-images.githubusercontent.com/17589/184540850-2fd2d574-2a02-45e0-b33e-5a042150cfde.gif)

Some unicode glyphs didn't render properly, other than that it looks alright, and it was generated in 4 seconds!

**Comment by ku1ik** [comment]
I also tried agg on @mathieu-aubin's 162519.cast:

![y](https://user-images.githubusercontent.com/17589/184541345-b4d4a84b-7e6f-47af-99f7-a7956b9d678c.gif)

Took 3 seconds, generated nice looking gif, although pretty heavy - 8.2 MB:

![162519](https://user-images.githubusercontent.com/17589/184541374-0bd8ff72-dcec-44eb-a865-efba080782bb.gif)

I then ran gifsicle on it - `gifsicle --lossy=80 -k 128 -O3 -Okeep-empty 162519.gif -o 162519-opt.gif` - which resulted in 4.4 MB gif, with some visible loss in quality, although still not terrible:

![162519-opt](https://user-images.githubusercontent.com/17589/184541433-c32416f4-da40-4298-ae48-3fdd48a2d9e9.gif)
