### ISSUE TITLE
Height overflow

### ISSUE THREAD

**Issue by AuHau** [asciinema/asciicast2gif#57]
I have bit longer cast ([here](https://asciinema.org/a/nnPnVVArpShePQFawJS8uTnHX)), that I tried to convert, but I wanted to limit the height of resulting GIF so I used the `-h` parameter. Unfortunately the resulted GIF trims the part that overflow the limited window.

I would expect that the tool will imitate terminal window behaviour where when the prompt reaches bottom of the window, it will start "push out" the oldest entries up and from the window view box. 

Is there some way to make this happen?

**Comment by mathieu-aubin** [comment]
Wouldnt it help to modify your cast file to the desired size and then try conversion?

**Comment by AuHau** [comment]
Hmm that did not occur to me, but how do I do that? I checked the `asciinema` help and did not find any way how to constrain the height...

**Comment by AuHau** [comment]
Hmm I figured out that resizing the terminal do the trick. 

But I still believe that it is sort of a bug and should be at least documented.

**Comment by mathieu-aubin** [comment]
From what i can read - altho yes i believe its not entirely clear - the readme uses the word « clip » rather than « wrap » or similar.

Does it make sense that « clip » would be litteral in this situation? You are more than welcome to submit a pr and i am certain that others will benefit from it.

@sickill any words on this?

**Comment by AuHau** [comment]
Hmmm as a non-native speaker, this might be then short-coming from my side. I would maybe then propose instead of "clip" use word "crop".

"Crop" is a quiet standard term in many graphical editors which describes this sort of behavior.

**Comment by ku1ik** [comment]
IMO both "clip" and "crop" are usually understood as something is cut off, which is different behaviour than what you expected (resizing of the virtual terminal). One way to change the virtual terminal size is to edit the .cast file and change the `width` / `height` attr to e.g. a lower value. This will make the virtual terminal used for rendering smaller, as if you were recording your session in a smaller terminal window in the first place.
