### ISSUE TITLE
Asciicast2gif crashes my pc while combining a gif file

### ISSUE THREAD

**Issue by r2dr0dn** [asciinema/asciicast2gif#65]
I Fixed The Problem By my Own Special Thanks To The team Who Developed This Tool That Full With Bugs :1st_place_medal:

**Comment by AndydeCleyre** [comment]
@doophack It would be much nicer to share *how* you fixed the problem here so others can benefit.

**Comment by mathieu-aubin** [comment]
yes. you really are a jerk. at least stop polluting and close this crappy issue

setting the scale to 1 would have also helped.
