### ISSUE TITLE
Produced GIF freezes when played

### ISSUE THREAD

**Issue by falzm** [asciinema/asciicast2gif#69]
Hi 👋 

I'm facing a very odd issue using asciicast2gif: it successfully produces a GIF file from an Asciinema cast file, however at some point the resulting GIF playback "freezes" (around frame 59 of 77). I tried on various players/browsers, all of them face the same problem. This is really weird, because when I open the GIF in macOS's Preview, all the frames are there... Do you know what could cause this?

Here is the command I'm running to generate the GIF (I run it via Docker):

```console
$ docker run --rm -ti -v $PWD:/data asciinema/asciicast2gif exo_1.4.0.cast exo_1.4.0.gif
==> Loading exo_1.4.0.cast...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Combining 77 screenshots into GIF file...
==> Done.
```

The input `.cast` file (suffixed with `.txt` because Github): [exo_1.4.0.cast.txt](https://github.com/asciinema/asciicast2gif/files/3315479/exo_1.4.0.cast.txt)

The resulting bogus GIF:

![exo_1 4 0](https://user-images.githubusercontent.com/1122379/59940394-ddc2a800-945a-11e9-8ce7-91d5816f1265.gif)

The correct Asciinema sequence can be played here: https://asciinema.org/a/4IXSk9XJ81aaDMmh0tTAqmjor

Thank you in advance!

**Comment by ku1ik** [comment]
Not sure why would that be... Either you can try https://github.com/asciinema/agg instead, which is a successor to asciicast2gif.

I generated gif from your recording with `agg`, looks like this:

![4IXSk9XJ81aaDMmh0tTAqmjor](https://user-images.githubusercontent.com/17589/184545998-7f10f7e0-8d23-4774-9dbd-f5f20dffe95c.gif)
