### ISSUE TITLE
[FR] change temp dir (improve documentation)

### ISSUE THREAD

**Issue by raidlman** [asciinema/asciicast2gif#73]
Depending on the length of the recorded cast, the png files can quickly grow in number and size. For systems with limited root file systems, converting casts to gif might clog the system by using too much of the available temp space under `/tmp`.

I figured you can change the temporary directory by setting the `TMPDIR` environment variable to tell the `mktemp` command to user another base directory. See [here](https://www.mktemp.org/manual.html).

It would be nice if this would be included in you docs.

**Comment by yangyang5214** [comment]
sounds good

**Comment by ku1ik** [comment]
Try https://github.com/asciinema/agg instead. It doesn't use any tmp space on disk.
