### ISSUE TITLE
Cache resources exhausted when converting to gif

### ISSUE THREAD

**Issue by spalladino** [asciinema/asciicast2gif#74]
On a [30s cast](https://asciinema.org/a/295214), when running the conversion with default parameters, I'm getting the following error, and the resulting gif is truncated:

```
convert-im6.q16: cache resources exhausted `/tmp/tmp.Xh5BmZC2by/41.png' @ error/cache.c/OpenPixelCache/4083.
```

I'm on node 10.13.0, gifsicle 1.92, and imagemagick 6.9.10-23, on Ubuntu 19.10. Thanks!

**Comment by niklashhh** [comment]
I have the same issue.

**Comment by niklashhh** [comment]
The problem got solved by commenting out all of the resource policies from `/etc/ImageMagick-6/policy.xml` file.

https://github.com/ImageMagick/ImageMagick/issues/396

**Comment by ku1ik** [comment]
You can also try https://github.com/asciinema/agg , which is a successor to asciicast2gif.
