### ISSUE TITLE
Option to add a delay to the last frame

### ISSUE THREAD

**Issue by zachriggle** [asciinema/asciicast2gif#76]
Currently, the generated GIF cycles rapidly, meaning the final output is hard to be able to read.

It would be useful if there could be a delay at the end, so that the results may be seen before the GIF loops.

This can be done with `imagemagick` with the following command, to set an e.g. 5 second delay.

```
convert $name.gif '(' -clone 0  ')' -swap 0 +delete '(' +clone -set delay 500 ')' +swap +delete $name-delay.gif
```

It would be nice to offer this as an option in asciicast2gif.

**Comment by ku1ik** [comment]
Closing as asciicast2gif is dead. Try https://github.com/asciinema/agg instead. agg doesn't support this yet but adding an option for this makes a lot of sense 👍
