### ISSUE TITLE
Certian grey text won't show

### ISSUE THREAD

**Issue by Heath123** [asciinema/asciicast2gif#78]
Compare
https://asciinema.org/a/9KVE2KEFNcZBupBnDWpsfZiqA
with
![demo](https://user-images.githubusercontent.com/13787163/111086785-1602f780-8516-11eb-87b3-a86de5ba3ce2.gif)
After I press Ctrl + C the text stays on my local terminal and the site, but not here

**Comment by ku1ik** [comment]
Closing as asciicast2gif is dead. Try https://github.com/asciinema/agg instead.
