### ISSUE TITLE
Fails with error write EPIPE on local file

### ISSUE THREAD

**Issue by yannham** [asciinema/asciicast2gif#79]
Trying to convert an existing local cast file always fails with `EPIPE`:
```
~asciinema rec
asciinema: recording asciicast to /tmp/tmpbmwoim06-ascii.cast
asciinema: press <ctrl-d> or type "exit" when you're done
~this is a test!
zsh: command not found: this
[1]    224148 exit 127   this is a test!
~[Ctrl+D] 
asciinema: recording finished
asciinema: press <enter> to upload to asciinema.org, <ctrl-c> to save locally
asciinema: asciicast saved to /tmp/tmpbmwoim06-ascii.cast
~cp /tmp/tmpbmwoim06-ascii.cast .
~asciicast2gif tmpbmwoim06-ascii.cast test.gif
==> Loading tmpbmwoim06-ascii.cast...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:774:11)
    at Socket._write (node:net:786:8)
    at writeOrBuffer (node:internal/streams/writable:395:12)
    at Socket.Writable.write (node:internal/streams/writable:340:10)
    at of (/usr/local/lib/node_modules/asciicast2gif/main.js:706:266)
    at Function.e [as c] (/usr/local/lib/node_modules/asciicast2gif/main.js:293:156)
    at /usr/local/lib/node_modules/asciicast2gif/main.js:295:256
    at /usr/local/lib/node_modules/asciicast2gif/main.js:295:280
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
[1]    224208 exit 1     asciicast2gif tmpbmwoim06-ascii.cast test.gif
```

System information:
- system: `Linux 5.10.0-5-amd64 #1 SMP Debian 5.10.26-1 (2021-03-27) x86_64 GNU/Linux`
- node: v15.14.0
- npm: v7.9.0
- asciinema2gif: upgraded to the last version available on NPM at the time of writing this issue

**Comment by AdmiralNemo** [comment]
I encountered this same error today.  It occurred when I tried to convert the same file locally or over HTTP.

**Comment by c12yptonic** [comment]
Same error experienced

**Comment by OlaoluwaM** [comment]
Same with node v17+. Error also occurs with remote conversion attempts

**Comment by trev-dev** [comment]
Also happening for me with Node version 16.14, local and remote

**Comment by initialjie** [comment]
Also happening for me with Node version 16.15, local and remote

**Comment by mathieu-aubin** [comment]
i dont have the issue - reinstall.. try again

`npm i asciicast2gif -g`

**Comment by trev-dev** [comment]
I definitely only have 1 global on path. What did work for me was following the docker instructions.

**Comment by mathieu-aubin** [comment]
make sure 'gifsicle' is installed, too

**Comment by trev-dev** [comment]
It was :)

**Comment by raspiduino** [comment]
I got the same issue :((

**Comment by mathieu-aubin** [comment]
Okay... well, then i have to say, without certainty, that its a file pdrmission issue. The user cant create/write file (or disk/partirion full) thus, the pipe fails.

How long does it take before it crashes after the output process status?

Why did you do this? That looks like an extra step that has no real good use and which can create some issues in some specific cases.
`~cp /tmp/tmpbmwoim06-ascii.cast .`

btw, as everything is a file under linux, it also include potential issues at creating folders or accessing them (i dont remember if the temporary png files get dumped to a folder while converting)

as i said before, i dont get this problem using same versions, on now 3 different sysrems. I can see potential for filesystem/permission issues and without more environment details... it doesnt seem to be software related is what i mean.

**Comment by raspiduino** [comment]
> Okay... well, then i have to say, without certainty, that its a file pdrmission issue. The user cant create/write file (or disk/partirion full) thus, the pipe fails.

I tried running everything with root permission but still got this issue

**Comment by trev-dev** [comment]
> > Okay... well, then i have to say, without certainty, that its a file pdrmission issue. The user cant create/write file (or disk/partirion full) thus, the pipe fails.
> 
> I tried running everything with root permission but still got this issue

With all of my respect for the writers of this software,  you should *never* have to run it as root. Just use the docker image if you have the stomach for it

**Comment by raspiduino** [comment]
> > > Okay... well, then i have to say, without certainty, that its a file pdrmission issue. The user cant create/write file (or disk/partirion full) thus, the pipe fails.
> > 
> > 
> > I tried running everything with root permission but still got this issue
> 
> With all of my respect for the writers of this software, you should _never_ have to run it as root. Just use the docker image if you have the stomach for it

I used docker but it failed with the same error :((

**Comment by jukefr** [comment]
having the same issue
```
asciicast2gif testing.json testing.gif
==> Loading testing.json...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:817:11)
    at Socket._write (node:net:829:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at of (/home/user/.node_modules_global/lib/node_modules/asciicast2gif/main.js:706:266)
    at Function.e [as c] (/home/user/.node_modules_global/lib/node_modules/asciicast2gif/main.js:293:156)
    at /home/user/.node_modules_global/lib/node_modules/asciicast2gif/main.js:295:256
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by mathieu-aubin** [comment]
I have no stake in this program and am not part of its develop team but this issue bugw me. It would be nice to have more infos on your environment so at least the issue could be reproducible. It would greatly help in determining  the  cause... 

whish you get it sorted...

**Comment by ku1ik** [comment]
Hey! I just published a successor to this tool: https://github.com/asciinema/agg - please try it instead. There will be no more work on asciicast2gif from me.
