### ISSUE TITLE
wsl install erro

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [asciinema/asciicast2gif#81]
![image](https://user-images.githubusercontent.com/28779327/126026314-8006b593-5ec5-44eb-96e9-e5fa9f3d061b.png)

**Comment by mathieu-aubin** [comment]
@wangwenqiangGitHub Was this the best way you figured to introduce an issue and attract relevant help? You should consider at least writti g a single word of your own, no?

**Comment by wangwenqiangGitHub** [comment]
I had success install asciicast2gif,but  it very slow
