### ISSUE TITLE
Add margins to generated GIFs

### ISSUE THREAD

**Issue by SkypLabs** [asciinema/asciicast2gif#82]
Hi,

It would be nice to be able to add margins to the generated GIFs. My use case is to improve the rendering of the [GitHub repositories' social media previews](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview).

The template that GitHub provides suggests to add 40px margins around the image.

**Comment by ku1ik** [comment]
Closing as asciicast2gif is dead. Try https://github.com/asciinema/agg instead.
