### ISSUE TITLE
cnpm install asciicast2gif error

### ISSUE THREAD

**Issue by Sanmejie** [asciinema/asciicast2gif#87]
system CentOS Linux release 7.6.1810 (Core)

logs：
`[19:08:22 root@master script]#cnpm install --global asciicast2gif
Downloading asciicast2gif to /usr/node-js/lib/node_modules/asciicast2gif_tmp
Copying /usr/node-js/lib/node_modules/asciicast2gif_tmp/_asciicast2gif@0.2.1@asciicast2gif to /usr/node-js/lib/node_modules/asciicast2gif
Installing asciicast2gif's dependencies to /usr/node-js/lib/node_modules/asciicast2gif/node_modules
[1/1] phantomjs-prebuilt@^2.1.16 installed at node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt
execute post install 1 scripts...
[1/1] scripts.install phantomjs-prebuilt@^2.1.16 run "node install.js", root: "/usr/node-js/lib/node_modules/asciicast2gif/node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt"
PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:209:13)
    at Pipe.<anonymous> (net.js:588:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2'
} Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:209:13)
    at Pipe.<anonymous> (net.js:588:12)
[npminstall:runscript:error] phantomjs-prebuilt@^2.1.16 scripts.install run "node install.js" error: Error [RunScriptError]: Run "sh -c node install.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/node-js/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:209:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  name: 'RunScriptError',
  stdio: [Object],
  exitcode: 1
}
Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
RunScriptError: Run "sh -c node install.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/node-js/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:209:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
npminstall version: 5.8.0
npminstall args: /usr/node-js/bin/node /usr/node-js/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com --global asciicast2gif
`

**Comment by Sanmejie** [comment]
`[19:12:11 root@master script]#npm install --global asciicast2gif
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/node-js/bin/asciicast2gif -> /usr/node-js/lib/node_modules/asciicast2gif/asciicast2gif

> phantomjs-prebuilt@2.1.16 install /usr/node-js/lib/node_modules/asciicast2gif/node_modules/phantomjs-prebuilt
> node install.js

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/node-js/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'asciicast2gif'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.9.1
4 verbose npm-session 374f58c1ae2229e5
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/asciicast2gif 1178ms (from cache)
8 silly pacote tag manifest for asciicast2gif@latest fetched in 1217ms
9 timing stage:loadCurrentTree Completed in 3185ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 9ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 268ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule asciicast2gif@0.2.1 checking installable status
17 silly removeObsoleteDep removing asciicast2gif@0.2.1 from the tree as its been replaced by a newer version or is no longer required
18 silly removeObsoleteDep removing phantomjs-prebuilt@2.1.16 from the tree as its been replaced by a newer version or is no longer required
19 silly removeObsoleteDep removing es6-promise@4.2.8 from the tree as its been replaced by a newer version or is no longer required
20 silly removeObsoleteDep removing extract-zip@1.7.0 from the tree as its been replaced by a newer version or is no longer required
21 silly removeObsoleteDep removing concat-stream@1.6.2 from the tree as its been replaced by a newer version or is no longer required
22 silly removeObsoleteDep removing buffer-from@1.1.2 from the tree as its been replaced by a newer version or is no longer required
23 silly removeObsoleteDep removing inherits@2.0.4 from the tree as its been replaced by a newer version or is no longer required
24 silly removeObsoleteDep removing readable-stream@2.3.7 from the tree as its been replaced by a newer version or is no longer required
25 silly removeObsoleteDep removing core-util-is@1.0.3 from the tree as its been replaced by a newer version or is no longer required
26 silly removeObsoleteDep removing inherits@2.0.4 from the tree as its been replaced by a newer version or is no longer required
27 silly removeObsoleteDep removing isarray@1.0.0 from the tree as its been replaced by a newer version or is no longer required
28 silly removeObsoleteDep removing process-nextick-args@2.0.1 from the tree as its been replaced by a newer version or is no longer required
29 silly removeObsoleteDep removing safe-buffer@5.1.2 from the tree as its been replaced by a newer version or is no longer required
30 silly removeObsoleteDep removing string_decoder@1.1.1 from the tree as its been replaced by a newer version or is no longer required
31 silly removeObsoleteDep removing safe-buffer@5.1.2 from the tree as its been replaced by a newer version or is no longer required
32 silly removeObsoleteDep removing util-deprecate@1.0.2 from the tree as its been replaced by a newer version or is no longer required
33 silly removeObsoleteDep removing typedarray@0.0.6 from the tree as its been replaced by a newer version or is no longer required
34 silly removeObsoleteDep removing debug@2.6.9 from the tree as its been replaced by a newer version or is no longer required
35 silly removeObsoleteDep removing ms@2.0.0 from the tree as its been replaced by a newer version or is no longer required
"~/.npm/_logs/2022-04-25T11_13_45_638Z-debug.log" 5677L, 386007C
`

**Comment by ku1ik** [comment]
If you still have this problem consider using [agg](https://github.com/asciinema/agg) instead.
